services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practica-clase-2-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
